/**
 *  导出所有的action类型
 */

export default {
    // 主题
    THEME_CHANGECOLOR:'THEME_CHANGECOLOR',
    THEME_INIT:'THEME_INIT',

    // HotPage数据加载
    HOT_REFRESH: 'HOT_REFRESH',
    HOT_LOAD_FAIL: 'HOT_LOAD_FAIL',
    HOT_LOAD_SUCCESS:'HOT_LOAD_SUCCESS',
    HOT_LOAD_MORE_SUCCESS: 'HOT_LOAD_MORE_SUCCESS',
    HOT_LOAD_MORE_FAIL: 'HOT_LOAD_MORE_FAIL',

    // 登录
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_NETFAIL: 'LOGIN_NETFAIL',
    CHANGE_SUCCESS: 'CHANGE_SUCCESS',
    CHANGE_FAIL: 'CHANGE_FAIL',
    CHANGE_NETFAIL: 'CHANGE_NETFAIL',
    
    // 收藏
    COLLECT_ACTION: 'COLLECT_ACTION'
}