/**
 *  导出所有的action类型
 */

export default {
    // 主题
    THEME_CHANGECOLOR:'THEME_CHANGECOLOR',
    THEME_INIT:'THEME_INIT',

    // HotPage数据加载
    HOT_REFRESH: 'HOT_REFRESH',
    HOT_LOAD_FAIL: 'HOT_LOAD_FAIL',
    HOT_LOAD_SUCCESS:'HOT_LOAD_SUCCESS',
    HOT_LOAD_MORE_SUCCESS: 'HOT_LOAD_MORE_SUCCESS',
    HOT_LOAD_MORE_FAIL: 'HOT_LOAD_MORE_FAIL'
}